server:
  servlet:
    context-path: /api
spring:
  application:
    name: sports-day-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://${LOCAL_STACK_HOST}:5432/sports_day}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:${LOCAL_STACK_HOST}:29092}
  data:
    redis:
      host: ${REDIS_HOST:${LOCAL_STACK_HOST}}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            clientId: ${CLIENT_ID:timesheets-service}
            clientSecret: ${CLIENT_SECRET:rX0uyWb89PxdeclkQoLMtmRtCLRxFlKy}
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_URL:https://sports-day-auth.${LOCAL_STACK_HOST}.nip.io:8085/realms/ratracejoe}

cors:
  ui-host: ${UI_DOMAIN:http://sports-day-ui.${LOCAL_STACK_HOST}.nip.io:9080}
logging:
  level:
    org:
      springframework:
        security: DEBUG
