services:
  app-db:
    image: postgres:latest
    container_name: sports-day-service
    networks:
      - sports-day
    environment:
      POSTGRES_USER: sportsAdmin
      POSTGRES_PASSWORD: SP%RTS
      POSTGRES_DB: sports_day
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka
    container_name: sports-day-audit
    networks:
      - sports-day
    ports:
      - "9092:9092"

  auth-db:
    image: postgres
    container_name: sports-day-auth-db
    networks:
      - sports-day
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_ROOT_PASSWORD: keycloak123
      POSTGRES_DB: auth
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: kc-password
    healthcheck:
      test: pg_isready -U keycloak -d auth
      interval: 10s
      timeout: 3s
      retries: 3

  auth:
    image: quay.io/keycloak/keycloak:22.0
    container_name: sports-day-auth
    networks:
      - sports-day
    command: start-dev --import-realm
    ports:
      - "8085:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin-pw
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://auth-db:5432/auth
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: kc-password
    depends_on:
      auth-db:
        condition: service_healthy
    volumes:
      - ./auth/:/opt/keycloak/data/import/:ro

networks:
  sports-day:
    driver: bridge

volumes:
  postgres_data:
