services:
  sports-day-db-migration:
    image: sports-day-db-migration
    container_name: sports-day-test-db-migration
    networks:
      - sports-day-db-test
    environment:
      LIQUIBASE_DRIVER: org.postgresql.Driver
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://${LOCAL_STACK}:5432/${SPORTS_DAY_DATABASE_NAME}
      LIQUIBASE_COMMAND_USERNAME: ${SPORTS_DAY_DATABASE_USERNAME}
      LIQUIBASE_COMMAND_PASSWORD: ${SPORTS_DAY_DATABASE_PASSWORD}
    depends_on:
      sports-day-test-db:
        condition: service_healthy

  sports-day-test-db:
    image: postgres:latest
    container_name: sports-day-test-db
    networks:
      - sports-day-db-test
    environment:
      POSTGRES_USER: ${SPORTS_DAY_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${SPORTS_DAY_DATABASE_PASSWORD}
      POSTGRES_DB: ${SPORTS_DAY_DATABASE_NAME}
    ports:
      - "${LOCAL_STACK}:5432:5432"
    volumes:
      - sports_day_test_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${SPORTS_DAY_DATABASE_USERNAME} -d ${SPORTS_DAY_DATABASE_NAME}
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  sports-day-db-test:
    driver: bridge

volumes:
  sports_day_test_data:
