spring:
  application:
    name: sports-day-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sports_day}
    username: sportsAdmin
    password: SP%RTS
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_URL:http://localhost:8085/realms/ratracejoe}

cors:
  ui-host: ${UI_DOMAIN:http://localhost:9080}