apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-day-audit
  labels:
    app: sports-day-audit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sports-day-audit
  template:
    metadata:
      labels:
        app: sports-day-audit
        app.kubernetes.io/name: sports-day-audit
    spec:
      containers:
        - name: sports-day-kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - name: kafka-port
              containerPort: 9092
          env:
            - name: KAFKA_KRAFT_MODE
              value: "true"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:9093"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
            - name: KAFKA_METADATA_LOG_DIR
              value: "/var/lib/kafka/metadata"
            - name: KAFKA_CLUSTER_ID
              value: "d28ed972-ff4d-11ef-8221-e7ed4ebc516c"
---
apiVersion: v1
kind: Service
metadata:
  name: sports-day-audit
spec:
  selector:
    app.kubernetes.io/name: sports-day-audit
  ports:
    - name: kafka-port
      protocol: TCP
      port: 9092
      targetPort: kafka-port
