apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-day-auth-db
  labels:
    app: sports-day-auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sports-day-auth-db
  template:
    metadata:
      labels:
        app: sports-day-auth-db
        app.kubernetes.io/name: sports-day-auth-db
    spec:
      containers:
        - name: sports-day-auth-db
          image: postgres:latest
          ports:
            - name: kc-db-port
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sports-day-auth-db-creds
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sports-day-auth-db-creds
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom: 
                  configMapKeyRef:
                    name: sports-day-auth-db-config
                    key: DATABASE_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: sports-day-auth-db
spec:
  selector:
    app.kubernetes.io/name: sports-day-auth-db
  ports:
    - name: kc-db-port
      protocol: TCP
      port: 5432
      targetPort: kc-db-port

