apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-day-audit
  labels:
    app: sports-day-audit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sports-day-audit
  template:
    metadata:
      labels:
        app: sports-day-audit
        app.kubernetes.io/name: sports-day-audit
    spec:
      containers:
        - name: sports-day-zk
          image: confluentinc/cp-zookeeper:7.4.4
          ports:
            - name: zk-port
              containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
        - name: sports-day-kafka
          image: confluentinc/cp-kafka:7.4.4
          ports:
            - name: kafka-port
              containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: localhost:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://sports-day-audit:9092,PLAINTEXT_HOST://sports-day-audit:29092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: sports-day-audit
spec:
  selector:
    app.kubernetes.io/name: sports-day-audit
  ports:
    - name: kafka-port
      protocol: TCP
      port: 29092
      targetPort: kafka-port
