apiVersion: batch/v1
kind: Job
metadata:
  name: sports-day-db-migration
spec:
  template:
    spec:
      containers:
      - name: sports-day-db-migration
        image: sports-day-db-migration:latest
        imagePullPolicy: Never
        env:
        - name: LIQUIBASE_DRIVER
          value: org.postgresql.Driver
        - name: LIQUIBASE_COMMAND_URL
          valueFrom: 
            configMapKeyRef:
              name: sports-day-db-config
              key: DATABASE_URL
        - name: LIQUIBASE_COMMAND_USERNAME
          valueFrom:
            secretKeyRef:
              name: sports-day-db-creds
              key: POSTGRES_USER
        - name: LIQUIBASE_COMMAND_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sports-day-db-creds
              key: POSTGRES_PASSWORD
      restartPolicy: Never
