apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-day-service
  labels:
    app: sports-day-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sports-day-service
  template:
    metadata:
      labels:
        app: sports-day-service
        app.kubernetes.io/name: sports-day-service
    spec:
      volumes:
        - name: jks-volume
          emptyDir: {}
        - name: ca-volume
          secret:
            secretName: sports-day-ca
        - name: key-volume
          secret:
            secretName: sports-day-service-tls
      initContainers:
        - name: tls-init
          image: openjdk:11
          command:
            - sh
            - -c
            - |
              keytool -import -alias ca -file /etc/tls/cert/sports-day.crt -keystore /etc/ssl/truststore.jks -storepass changeit -noprompt
              keytool -import -alias tls -file /etc/tls/key/tls.crt -keystore /etc/ssl/keystore.jks -storepass changeit -noprompt
          volumeMounts:
            - name: jks-volume
              mountPath: /etc/ssl
            - name: ca-volume
              mountPath: /etc/tls/cert
              readOnly: true
            - name: key-volume
              mountPath: /etc/tls/key
              readOnly: true
      containers:
        - name: sports-day-service
          image: sports-day-service:latest
          imagePullPolicy: Never
          ports:
            - name: http-web-svc
              containerPort: 8080
          volumeMounts:
            - name: jks-volume
              mountPath: /etc/ssl
            - name: ca-volume
              mountPath: /etc/tls/cert
              readOnly: true
            - name: key-volume
              mountPath: /etc/tls/key
              readOnly: true
          env:
            - name: DB_URL
              valueFrom: 
                configMapKeyRef:
                  name: sports-day-db-config
                  key: DATABASE_URL
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: sports-day-db-config
                  key: DATABASE_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sports-day-db-creds
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sports-day-db-creds
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              value: sports-day-cache
            - name: REDIS_PORT
              value: "6379"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: sports-day-audit:9092
            - name: OAUTH2_URL
              value: https://sports-day-auth.local/realms/ratracejoe
            - name: UI_DOMAIN
              value: https://sports-day-ui.local
            - name: JAVA_OPTS
              value: > 
                -Djavax.net.ssl.trustStore=/etc/ssl/truststore.jks 
                -Djavax.net.ssl.trustStorePassword=changeit 
                -Djavax.net.ssl.keyStore=/etc/ssl/keystore.jks 
                -Djavax.net.ssl.keyStorePassword=changeit
---
apiVersion: v1
kind: Service
metadata:
  name: sports-day-service
spec:
  selector:
    app.kubernetes.io/name: sports-day-service
  ports:
    - name: service-port
      protocol: TCP
      port: 8080
      targetPort: http-web-svc

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sports-day-service
spec:
  tls:
    - hosts:
        - sports-day-service.local
      secretName: sports-day-service-tls
  rules:
    - host: sports-day-service.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sports-day-service
                port:
                  name: service-port


