FROM amazoncorretto:21-alpine-jdk
LABEL authors="joesharpcs.co.uk"
COPY build/libs/sports-day-service-0.0.1-SNAPSHOT.jar sports-day-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/sports-day-service-0.0.1-SNAPSHOT.jar"]
